#!/usr/bin/env bash
set -exu

mkdir build
cd build

cmake ${CMAKE_ARGS} \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DWITH_PYTHON=ON \
    -DWITH_ROOT=ON \
    -DWITH_EXAMPLES=ON \
    -DWITH_EXAMPLES_EXTRA=OFF \
    -DENABLE_TESTS=OFF \
    -DBUILD_DOCUMENTATION=OFF \
    -DINSTALL_EXTERNAL_DEPENDENCIES=OFF \
    -DFORCE_YAMLCPP_INSTALL=OFF \
    -DFORCE_HEPMC_INSTALL=OFF \
    -DPython3_EXECUTABLE="$PYTHON" \
    ..

make -j${CPU_COUNT}
make install
