{% set name = "hammer" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/mpapucci/Hammer/-/archive/v{{ version }}/Hammer-v{{ version }}.tar.gz
  sha256: b40de8a9685ca581d34b978c208c4dcf82b0c195489e9b6388a4c8f191e97283
  patches:
    - 0001-Add-missing-includes.patch

build:
  number: 0
  skip: true  # [win or py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - python
    - root_base
    - boost-cpp
    - hepmc2
    - yaml-cpp
    - numpy
    - matplotlib-base
    - cython
    - cymove
    - setuptools
  run:
    - python
    - boost-cpp
    - yaml-cpp
    - hepmc2
    - {{ pin_compatible('numpy') }}
    - matplotlib-base
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  imports:
    - hammer
  commands:
    - cd $CONDA_PREFIX/share/Hammer/examples
    - ./demo01
    - ./demo01card
    - ./demo01root
    - ./demo02
    - ./demo02root
    - ./demo03
    - ./demo03root
    - ./demo04
    # Disabled due to being very slow
    # - ./demo04parallel
    - ./demo04root
    - ./demo04root2
    - ./demo05
    - ./demo07
    - ./demo08
    - ./demo09
    - ./demo10
    - python demo03.py
    - python demo04.py

about:
  home: https://hammer.physics.lbl.gov/
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: Helicity Amplitude Module for Matrix Element Reweighting

  description: |
    A C++ software library, designed to provide fast and efficient reweighting
    of large Monte Carlo datasets containing semileptonic b-Hadron decays to
    any desired New Physics, or to any description of the hadronic matrix
    elements. See the HAMMER website for more information.
  doc_url: https://hammer.physics.lbl.gov/HammerManual.pdf
  dev_url: https://gitlab.com/mpapucci/Hammer

extra:
  recipe-maintainers:
    - chrisburr
